# gutclip/configs/default.yaml
# ============================================================
name: gutclip_exp
seed: 42

# -------- 训练超参 ------------------------------------------
epochs: 1000
patience: 200
min_delta: 0.001
batch_size: 128
num_workers: 4
lr: 1e-4
wd: 0.001
logit_lr_factor: 0.05
warmup_epochs: 5
precision: amp          # amp / fp32
max_grad_norm: 1.0
local_loss: true        # true=单卡，false=跨卡 gather
log_interval: 50

# -------- 方差正则 (三项中的第③) -----------------------------
var_gamma: 1.0          # γ，下限
var_weight: 0.01        # λ，正则权重


# -------- 模型维度 ------------------------------------------
tree_dim: 256
dna_dim: 768
embed_dim: 1280

# -------- 稀疏感知专属 (三项中的第②) ------------------------
sparse:
  zero_weight_init: 0.9     # 可学习 zero_weight 的初值 (0~1)
  detection_threshold: 0.0  # <阈值 视为 0 丰度
  augment_ratio: 0.1        # 如需用到的数据增强占比

# -------- 数据路径 ------------------------------------------
data:
  type: split
  train_meta: /data/home/wudezhi/project/school/x-meta/datasets/V3_34806/train_meta.csv   # 训练集元数据
  val_meta:  /data/home/wudezhi/project/school/x-meta/datasets/V3_34806/val_meta.csv      # 验证集元数据

  dna_dir:   /data/home/wudezhi/project/school/x-meta/datasets/raw/dna_embeddings_v3
  tree_dir:  /data/home/wudezhi/project/school/x-meta/datasets/raw/tree     

  dna_ext:  .pt
  tree_ext: .pt

  max_genes: 1024
  augment:
    enable: true
    edge_drop: 0.1
    feat_noise: 0.1
    coord_noise: 0.01

# -------- wandb ---------------------------------------------
wandb:
  project: gutclip
  mode: offline            # online / offline / disabled
