defaults:
  - defaults: default
  - model: diffusion
  - _self_

run_name: gutclip_diffusion_v1
seed: 42

data:
  train_embed_pt: datasets/diffusion/V3/train_embeddings.pt
  val_embed_pt:   datasets/diffusion/V3/valid_embeddings.pt

retrieval:
  index: datasets/diffusion/V3/faiss_index.faiss
  y:     datasets/diffusion/V3/faiss_index.y.npy
  ids:   datasets/diffusion/V3/faiss_index.ids.npy
  k: 5
  metric: l2               # 或 ip
  softmax_temp: 0.1        # 温度（越小越尖锐）
  sim_thresh: null         # 可设为 0.0~3.0（视 metric/S 的标度）

#── 训练超参 ───────────────────────
train:
  epochs:           250
  batch_size:        128
  weight_decay:    1e-2
  scheduler_type:  ddpm
  num_timesteps:   1000
  warmup_steps:     500
  grad_clip:       0.5          # 与 max_grad_norm 二选一；代码会兜底读取
  precision:       amp
  lambda_rank:     0.1
  log_interval:     50
  save_ckpt_every:  5000
  patience:        20
  min_delta:       1e-6

  # 高SNR采样/校准
  sigma_min: 0.03
  logsnr_min: -6.0
  logsnr_max: 8.0
  p_high_snr: 1.0            # 前 1-2 个 epoch 可用 1.0，之后改 0.6~0.7
  lambda_high: 0.22
  lambda_mag: 3.0
  lambda_ang: 0.6
  lambda_norm: 0.50
  lambda_ortho: 0.6
  high_snr_center: 5.9
  high_snr_tau: 0.6
  gamma_min_snr: 6.0

  # 学习率
  lr: 1.0e-4

  # 融合损失与正则
  lambda_fuse: 0.1
  lambda_reg: 1.0e-4

# ── 数据加载 ───────────────────────
num_workers: 4

# ── 推断 / 采样 ───────────────────
sampler:
  steps:            50
  guidance_scale: 1.0
  eta:             0.0
  temperature:     1.0

# ── 日志 / 监控 ───────────────────
wandb:
  project: gutclip
  mode:     offline
  notes:    "FiLM-UNet1D + softmax-kNN prior + FusionHead"